version: "3.7"
services:

  transmission:
    image: linuxserver/transmission
    env_file:
      - transmission.env
    volumes:
      - ./data/transmission/downloads:/downloads
      - ./data/transmission/watch:/watch
      - ./data/transmission/config:/config
    ports:
      - 80:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always

  sync:
    image: linuxserver/resilio-sync
    volumes:
      - ./resilio:/config
      - ./cache:/downloads
      - ./data/transmission:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: always
